class_name BioShieldVisual
extends MeshInstance3D

## BioShieldVisual — Energy shield bubble around the player ship.
##
## Uses the nojoule Interactive Energy Shield shader (res://addons/energy_shield/shield.gdshader)
## to render a rippling impact effect at hit locations and a strength-driven base glow.
##
## Visibility rules:
##   • Full shield  → invisible (only the impact flash/ripple appears on hit)
##   • Damaged      → persistent glow that brightens and shifts toward warning red as it depletes
##   • Depleted     → hidden (no shield bubble)
##
## The node is meant to be parented to the ship body so it follows the ship transform.

## Maximum simultaneous impact ripples the shader can render.
const _MAX_IMPACTS: int = 5

## Base color of the shield at full strength (bio-cyan).
@export var shield_color: Color = Color(0.26, 0.975, 1.0, 1.0)
## Warning tint blended in as the shield depletes (0 = full, 1 = depleted).
@export var warning_color: Color = Color(1.0, 0.32, 0.28, 1.0)
## Radius of the shield bubble in local units (should encompass the ship mesh).
@export var bubble_radius: float = 16.0
## Time for a single impact ripple to travel across the shield surface.
@export var anim_time: float = 2.5
## Brightness of the persistent glow when the shield is damaged (low end).
@export var min_glow_brightness: float = 3.0
## Brightness of the persistent glow when the shield is nearly depleted (high end).
@export var max_glow_brightness: float = 11.0
## Brightness of the impact flash ripple.
@export var impact_brightness: float = 14.0

var _material: ShaderMaterial
var _curve: Curve
var _current_impact: int = 0
var _animate: Array[bool] = []
var _elapsed_time: Array[float] = []
var _impact_origin: Array[Vector3] = []
var _strength: float = 1.0
var _initialized: bool = false


func _ready() -> void:
	_build_shield()
	_initialized = _material != null
	if _initialized:
		set_strength(1.0)


func _build_shield() -> void:
	# Load shader resources from the energy_shield addon.
	var shader: Shader = load("res://addons/energy_shield/shield.gdshader") as Shader
	if shader == null:
		push_warning("BioShieldVisual: energy shield shader failed to load — shield disabled.")
		return
	var noise_tex: Texture2D = load("res://addons/energy_shield/shield_noise.tres") as Texture2D
	_curve = load("res://addons/energy_shield/impact_animation_curve.tres") as Curve

	# Build the per-instance shader material.
	_material = ShaderMaterial.new()
	_material.resource_local_to_scene = true
	_material.shader = shader

	# --- General ---
	_material.set_shader_parameter("_quantization", true)
	_material.set_shader_parameter("_steps_quantization", 5)
	_material.set_shader_parameter("_object_scale", 1.0)
	_material.set_shader_parameter("_object_size", bubble_radius * 2.0)

	# --- Visibility: invisible at full strength (only impact waves show) ---
	_material.set_shader_parameter("_only_on_wave_visibility", true)
	_material.set_shader_parameter("_start_falloff_visibility", 0.5)
	_material.set_shader_parameter("_end_falloff_visibility", 0.3)
	_material.set_shader_parameter("_time_multiplier_activation", 2.0)
	_material.set_shader_parameter("_distance_multiplier_activation", 1.0)
	_material.set_shader_parameter("_width_time_activation", 0.2)

	# --- Intersection highlight ---
	_material.set_shader_parameter("_enable_highlight_intersection", true)
	_material.set_shader_parameter("_width_highlight_intersection", 1.0)

	# --- Noise ---
	if noise_tex:
		_material.set_shader_parameter("_noise_texture", noise_tex)
	_material.set_shader_parameter("_speed_noise", Vector2(0.02, 0.02))

	# --- Generate/Collapse (fully generated by default) ---
	_material.set_shader_parameter("_origin_generate", Vector3(0.0, 0.5, 0.0))
	_material.set_shader_parameter("_time_generate", 1.0)
	_material.set_shader_parameter("_thickness_generate", 0.25)
	_material.set_shader_parameter("_collapse", false)

	# --- Shield color ---
	_material.set_shader_parameter("_color_shield", shield_color)
	_material.set_shader_parameter("_color_brightness_shield", impact_brightness)
	_material.set_shader_parameter("_intensity_shield", 2.5)
	_material.set_shader_parameter("glow_enabled", true)
	_material.set_shader_parameter("glow_strength", 0.1)

	# --- Static ripple (subtle ambient surface motion) ---
	_material.set_shader_parameter("_active_static", true)
	_material.set_shader_parameter("_origin_static", Vector3(0.0, 0.5, 0.0))
	_material.set_shader_parameter("_speed_static", 0.1)
	_material.set_shader_parameter("_frequency_static", 80.0)
	_material.set_shader_parameter("_amplitude_static", 0.002)
	_material.set_shader_parameter("_normal_amplitude_static", 0.002)
	_material.set_shader_parameter("_effect_radius_static", bubble_radius * 1.5)
	_material.set_shader_parameter("_active_static_offset_hl", true)
	_material.set_shader_parameter("_strength_static_offset_hl", 1.0)
	_material.set_shader_parameter("_intensity_static_offset_hl", 5.0)
	_material.set_shader_parameter("_relative_origin_static", true)

	# --- Impact ripple ---
	_material.set_shader_parameter("_frequency_impact", 20.0)
	_material.set_shader_parameter("_waves_impact", 0.0)
	_material.set_shader_parameter("_fade_waves_impact", 2.0)
	_material.set_shader_parameter("_amplitude_impact", 0.02)
	_material.set_shader_parameter("_normal_amplitude_impact", 0.05)
	_material.set_shader_parameter("_radius_impact", bubble_radius)
	_material.set_shader_parameter("_active_impact_offset_hl", true)
	_material.set_shader_parameter("_strength_impact_offset_hl", 1.0)
	_material.set_shader_parameter("_intensity_impact_offset_hl", 5.0)
	_material.set_shader_parameter("_relative_origin_impact", true)

	# Initialize impact uniform arrays (shader expects vec3[5] / float[5]).
	var origins := PackedVector3Array()
	var times := PackedFloat32Array()
	for _i in _MAX_IMPACTS:
		origins.append(Vector3.ZERO)
		times.append(0.0)
		_animate.append(false)
		_elapsed_time.append(0.0)
		_impact_origin.append(Vector3.ZERO)
	_material.set_shader_parameter("_origin_impact", origins)
	_material.set_shader_parameter("_time_impact", times)

	# Build the bubble sphere mesh.
	var sphere := SphereMesh.new()
	sphere.resource_local_to_scene = true
	sphere.material = _material
	sphere.radius = bubble_radius
	sphere.height = bubble_radius * 2.0
	sphere.radial_segments = 96
	sphere.rings = 64
	mesh = sphere

	# The shield is a transparent additive-style effect — disable shadow/GI contribution.
	cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	gi_mode = GeometryInstance3D.GI_MODE_DISABLED


func _physics_process(delta: float) -> void:
	if not _initialized or not _material:
		return

	# Advance active impact ripple animations.
	var any_update := false
	var time_impacts := PackedFloat32Array()
	for _i in _MAX_IMPACTS:
		time_impacts.append(0.0)

	for impact_id in _MAX_IMPACTS:
		if _animate[impact_id]:
			any_update = true
			if _elapsed_time[impact_id] < anim_time:
				var normalized: float = _elapsed_time[impact_id] / anim_time
				time_impacts[impact_id] = _curve.sample(normalized) if _curve else normalized
				_elapsed_time[impact_id] += delta
			else:
				time_impacts[impact_id] = 0.0
				_elapsed_time[impact_id] = 0.0
				_animate[impact_id] = false

	if any_update:
		_material.set_shader_parameter("_time_impact", time_impacts)

	# Keep the shader's object scale in sync with node scale.
	var new_scale: float = max(
		global_transform.basis.get_scale().x,
		max(global_transform.basis.get_scale().y, global_transform.basis.get_scale().z)
	)
	_material.set_shader_parameter("_object_scale", new_scale)


## Trigger a rippling impact flash at [param world_pos] (in world space).
## If [param world_pos] is Vector3.ZERO, a fallback point on the bubble is used.
func trigger_impact(world_pos: Vector3) -> void:
	if not _initialized or not _material:
		return

	var local_pos: Vector3
	if world_pos == Vector3.ZERO:
		local_pos = _fallback_impact_point()
	else:
		local_pos = to_local(world_pos)
	# Clamp the impact origin to the bubble surface so the ripple emanates from the
	# closest point on the shield — this is what the shader expects.
	if local_pos.length() > 0.001:
		local_pos = local_pos.normalized() * bubble_radius

	_animate[_current_impact] = true
	_elapsed_time[_current_impact] = 0.0
	_impact_origin[_current_impact] = local_pos

	var origins := PackedVector3Array()
	for i in _MAX_IMPACTS:
		origins.append(_impact_origin[i])
	_material.set_shader_parameter("_origin_impact", origins)
	_material.set_shader_parameter("_relative_origin_impact", true)

	# Push an immediate (t=0) sample so the flash is visible on the same frame.
	var times := PackedFloat32Array()
	for i in _MAX_IMPACTS:
		if _animate[i] and _elapsed_time[i] < anim_time:
			var n: float = _elapsed_time[i] / anim_time
			times.append((_curve.sample(n) if _curve else n))
		else:
			times.append(0.0)
	_material.set_shader_parameter("_time_impact", times)

	_current_impact = (_current_impact + 1) % _MAX_IMPACTS

	# Ensure the node is visible while a ripple is playing even at full strength.
	visible = true


## Set the shield strength ratio [0.0 .. 1.0].
## 1.0 = full (invisible except impacts), 0.0 = depleted (hidden).
func set_strength(ratio: float) -> void:
	_strength = clampf(ratio, 0.0, 1.0)
	if not _initialized or not _material:
		return

	if _strength <= 0.001:
		# Shield depleted — no bubble.
		visible = false
		return

	visible = true
	var warn: float = 1.0 - _strength

	if _strength >= 0.999:
		# Full shield: invisible except on impact waves.
		_material.set_shader_parameter("_only_on_wave_visibility", true)
		_material.set_shader_parameter("_color_brightness_shield", impact_brightness)
		_material.set_shader_parameter("_color_shield", shield_color)
	else:
		# Damaged: persistent glow that brightens as the shield depletes, tinting
		# toward the warning color so the player reads the danger.
		_material.set_shader_parameter("_only_on_wave_visibility", false)
		var brightness: float = lerp(min_glow_brightness, max_glow_brightness, warn)
		_material.set_shader_parameter("_color_brightness_shield", brightness)
		var col := Color(
			lerp(shield_color.r, warning_color.r, warn * 0.7),
			lerp(shield_color.g, warning_color.g, warn * 0.7),
			lerp(shield_color.b, warning_color.b, warn * 0.7),
			1.0
		)
		_material.set_shader_parameter("_color_shield", col)


## Returns the current strength ratio [0..1].
func get_strength() -> float:
	return _strength


## Pick a plausible impact point on the bubble when no hit position is supplied.
## Uses the ship's travel direction (impacts generally come from ahead) or a
## random surface point when stationary.
func _fallback_impact_point() -> Vector3:
	var dir: Vector3 = Vector3.ZERO
	var parent_node: Node3D = get_parent() as Node3D
	if parent_node and parent_node.has_method("get") and "linear_velocity_vector" in parent_node:
		var vel: Vector3 = parent_node.get("linear_velocity_vector")
		if vel.length() > 0.1:
			dir = vel.normalized()
	if dir == Vector3.ZERO:
		# Random point on a sphere.
		var rng := RandomNumberGenerator.new()
		dir = Vector3(rng.randf_range(-1.0, 1.0), rng.randf_range(-1.0, 1.0), rng.randf_range(-1.0, 1.0)).normalized()
	# Convert world-space direction to local-space surface point.
	return (global_transform.basis.inverse() * dir).normalized() * bubble_radius
